<div id="welcome">
<h4><?= $this->escape($this->message) ?></h4>
</div>

<?php if($this->loggedRole):?>
<p>You can't manage delegations logged in as a Role.</p>
<?php else:?>

	<h3>Delegation Management</h3>
	
	
	<?php if($this->form):?>
	<div class="form">
	    <?=$this->form?>
	</div>
	<?php endif; ?>
	
	
	<?php if($this->delegationList):?>
		<h3>Delegation List</h3>
		<table cellpadding="10" border="1" cellspacing="0">
		<tr>
			<th>Delegator</th>
			<th>Delegate</th>
			<th>Scopes</th>
			<th>Expiration date</th>
			<th>Operations</th>
		</tr>
		<?php foreach($this->delegationList as $d): ?>
			<tr>
				<td><?=$d->getDelegator()?></td>
				<td><?=$d->getDelegate()?></td>
				<td><?=$d->getScopes()?></td>
				<td><?=$d->getExpDate()?></td>
				<td>
					<a href="<? echo $this->url( array('controller' => 'management', 'action' => 'edit') ); ?>?delegator=<?=$d->getDelegator()?>&delegate=<?=$d->getDelegate()?>">edit</a>
					<a href="<? echo $this->url( array('controller' => 'management', 'action' => 'delete') ); ?>?delegator=<?=$d->getDelegator()?>&delegate=<?=$d->getDelegate()?>">remove</a>
				</td>
			</tr>
		<?php endforeach;?>
		</table>
	<?php else:?> <p>There is no delegation made by you</p>
	<?php endif;?>
	
	
	<?php if($this->receivedDelegations):?>
		<h3>Received Delegations</h3>
		<table cellpadding="10" border="1" cellspacing="0">
		<tr>
			<th>Delegator</th>
			<th>Delegate</th>
			<th>Scopes</th>
			<th>Expiration date</th>
			<th>Operations</th>
		</tr>
		<?php foreach($this->receivedDelegations as $d): ?>
			<tr>
				<td><?=$d->getDelegator()?></td>
				<td><?=$d->getDelegate()?></td>
				<td><?=$d->getScopes()?></td>
				<td><?=$d->getExpDate()?></td>
				<td>
					<a href="<? echo $this->url( array('controller' => 'management', 'action' => 'delete') ); ?>?delegator=<?=$d->getDelegator()?>&delegate=<?=$d->getDelegate()?>">remove</a>
				</td>
			</tr>
		<?php endforeach;?>
		</table>
	<?php else:?> <p>There is no received delegation</p>
	<?php endif;?>
	
	
	<?php if($this->pendingDelegationsSent):?>
		<h3>Pending Delegations sent</h3>
		<table cellpadding="10" border="1" cellspacing="0">
		<tr>
			<th>Delegator</th>
			<th>Delegate</th>
			<th>Scopes</th>
			<th>Expiration date</th>
			<th>Operations</th>
		</tr>
		<?php foreach($this->pendingDelegationsSent as $d): ?>
			<tr>
				<td><?=$d->getDelegator()?></td>
				<td><?=$d->getDelegate()?></td>
				<td><?=$d->getScopes()?></td>
				<td><?=$d->getExpDate()?></td>
				<td>
					<a href="<? echo $this->url( array('controller' => 'management', 'action' => 'revoke') ); ?>?delegator=<?=$d->getDelegator()?>&delegate=<?=$d->getDelegate()?>">revoke</a>
				</td>
			</tr>
		<?php endforeach;?>
		</table>
	<?php else:?> <p>There is no pending delegation sent</p>
	<?php endif;?>
	
	
	<?php if($this->pendingDelegationsReceived):?>
		<h3>Pending Delegations received</h3>
		<table cellpadding="10" border="1" cellspacing="0">
		<tr>
			<th>Delegator</th>
			<th>Delegate</th>
			<th>Scopes</th>
			<th>Expiration date</th>
			<th>Operations</th>
		</tr>
		<?php foreach($this->pendingDelegationsReceived as $d): ?>
			<tr>
				<td><?=$d->getDelegator()?></td>
				<td><?=$d->getDelegate()?></td>
				<td><?=$d->getScopes()?></td>
				<td><?=$d->getExpDate()?></td>
				<td>
					<a href="<? echo $this->url( array('controller' => 'management', 'action' => 'verifydelegation') ); ?>?code=<?=$d->getCode()?>">accept</a>
					<a href="<? echo $this->url( array('controller' => 'management', 'action' => 'revoke') ); ?>?delegator=<?=$d->getDelegator()?>&delegate=<?=$d->getDelegate()?>">deny</a>
				</td>
			</tr>
		<?php endforeach;?>
		</table>
	<?php else:?> <p>There is no pending delegation received</p>
	<?php endif;?>
	
<?php endif;?>